// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-RAzbfNoDwXuSaiEZp9cf0uxsNTB72QQ',
    appId: '1:325358194954:web:a556a22c4995c82a0eaaf3',
    messagingSenderId: '325358194954',
    projectId: 'nti-r3-884c6',
    authDomain: 'nti-r3-884c6.firebaseapp.com',
    storageBucket: 'nti-r3-884c6.firebasestorage.app',
    measurementId: 'G-91ZTJT7329',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJWxczp8mqhhMIoQts8O7d-wDDr9z18Aw',
    appId: '1:325358194954:android:688dc177f27b71120eaaf3',
    messagingSenderId: '325358194954',
    projectId: 'nti-r3-884c6',
    storageBucket: 'nti-r3-884c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG2Fqt8_PPg6n4M9O6x1qJwvJhMQvSQHY',
    appId: '1:325358194954:ios:c54704b501bc8c460eaaf3',
    messagingSenderId: '325358194954',
    projectId: 'nti-r3-884c6',
    storageBucket: 'nti-r3-884c6.firebasestorage.app',
    iosBundleId: 'com.example.ntiRound3',
  );
}
